### PR TITLE
[WIP] Allow diffing on-the-fly round 2

### PR DESCRIPTION
**Pull request by PythonNut**
This should address some of the issues.

However, I can't seem to reproduce saving before the idle timer fires. It's still updating for me.

### CODE REVIEW

**Comment by PythonNut** [comment]
p.s. I have this in my init:

```emacs
(setq
  lisp-indent-offset 2
  lisp-body-indent 2)
```

IMHO it makes the indentation less consistent but easier to parse (at least for me) and more like other languages.

**Comment by dgutov** [comment]
> However, I can't seem to reproduce saving before the idle timer fires.

That's odd. It reproduces every time I try. Maybe I'll have to dig deeper.

> I have this in my init:

Please don't do that. Emacs Lisp already has well-established indentation offsets, and when you contribute to other projects using non-default indentation settings, you risk adding spurious indentation changes. Or if you don't, I'll probably end up doing them at some point, when editing your code.

**Comment by PythonNut** [comment]
> Please don't do that.

That was a setting I added last year when I started Emacs. it [shouldn't happen again](https://github.com/PythonNut/emacs-config/commit/e8ea15d70d5573181bac9df3e6c61fac43f66a01).

**Comment by dgutov** [comment]
Thank you!

Now, could you explain the reason to use `diff-hl-with-diff-switches` here?

**Comment by PythonNut** [comment]
@dgutov because of [this commit](https://github.com/PythonNut/diff-hl/commit/cbba426c4ac8dff0a8c1b866f1d4f09620cef3c9).

**Comment by PythonNut** [comment]
For some reason canceling the idle timer doesn't work for me. Do you see this?

**Comment by dgutov** [comment]
> @dgutov because of this commit.

I see. Well... it doesn't seem appropriate. AFAICS, we need `diff-switches` and `vc-` bindings in different situations, so there's no need in putting them together.

**Comment by dgutov** [comment]
> For some reason canceling the idle timer doesn't work for me.

Not sure. How do I reproduce this?

**Comment by PythonNut** [comment]
Try turning `diff-hl-flyspell-mode` off. The timer hangs around and starts causing errors because the advice is no longer active.

**Comment by dgutov** [comment]
It gets disabled: I see no errors after turning `diff-hl-flydiff-mode` off, and `timer-idle-list` doesn't list `diff-hl-update` after that either. Using Emacs master.

I also can't seem to reproduce the "saving before the timer fires" problem either. :confused:

**Comment by dgutov** [comment]
Where did the change that created a user option go?

If you like, please open a new pull request based on the current master.

**Comment by PythonNut** [comment]
Dang, @dgutov is there anything that still needs doing? Sorry I was gone, it looks like you've finished it all up.

**Comment by dgutov** [comment]
Yup. :)

I'm not using the new mode day-to-day (yet). So please be on a lookout for any new problems.

**Comment by PythonNut** [comment]
I will. I'm using it day-to-day so hopefully things that can pop up will pop up.

**Pull request closed without merging**
