### PR TITLE
Make `diff-hl-revert-hunk` work on narrowed buffers

### PR DESCRIPTION
**Pull request by edkolev**
This PR tweaks `diff-hl-revert-hunk` to make it work on narrowed buffers. Let me know if the PR can be improved!

Thanks for this package!

### CODE REVIEW

**Comment by dgutov** [comment]
Hmm. Aren't you worried that this way the command will affect the buffer contents beyond the current narrowing?

And does the subsequent `vc-exec-after` really work fine within the narrowing?

**Comment by edkolev** [comment]
> And does the subsequent vc-exec-after really work fine within the narrowing?

After some more testing - I see that it only works when reverting a hunk which adds lines. Reverting a hunk which deletes lines restores the lines in incorrect place.

Also, as you hinted, it doesn't work correctly if the hunk is partially in the narrowed region - instead of reverting the hunk, a message "Hunk hasn't been applied yet; apply it now? (y or n)" is displayed.

Do you think the following behaviour is adequate: the `diff-hl-revert-hunk`'s body could be wrapped  in a `(save-restriction (widen) ...)`. As a result, the buffer will be widened temporarily while the user is being asked "Revert current hunk in %s?".

Alternatively, I could try to achieve this behaviour: when hunk isn't 100% within the narrowed buffer, show a `(user-error "Can't revert a hunk which isn't within the narrowed buffer")`. This approach seems better from the user's stand point, but it would require a bit more changes in the code.

**Comment by dgutov** [comment]
> Do you think the following behaviour is adequate

What do *you* think? You filed with issue with some particular behavior in mind, right?

> when hunk isn't 100% within the narrowed buffer, show a (user-error

That sounds okay to me, and will probably result in a shorter diff.

**Comment by edkolev** [comment]
> That sounds okay to me, and will probably result in a shorter diff.

I've now implemented this behaviour, which makes the most sense to me - if the hunk is outside of the narrowed region, user-error. Otherwise, revert the hunk, preserving the narrowed region.

In case the code/behaviour can be improved - please let me know.

**Comment by dgutov** [comment]
Sorry for the long wait.

After looking at the patch, it's more complicated than I would like, especially for a feature I'd like to "just work" but never test in practice.

How about we revert to the approach you mentioned?

> the diff-hl-revert-hunk's body could be wrapped in a (save-restriction (widen) ...). As a result, the buffer will be widened temporarily while the user is being asked "Revert current hunk in %s?"

I'm fine with it, and while the diff is longer, the increase in complexity is small.

@edkolev, do you have any objections against this solution yourself, as a user of narrowed buffers? I have to ask because I never use narrowing interactively.

**Comment by edkolev** [comment]
> @edkolev, do you have any objections against this solution yourself, as a user of narrowed buffers? I have to ask because I never use narrowing interactively.

No, this seems fine. Reverting a hunk in a narrowed buffer isn't something that I do on a regular basis, so as long as it works correctly it's great. Having the buffer widen temporarily is perfectly fine.

I've updated the code in this PR.

**Comment by dgutov** [comment]
Thanks!

**Pull request merged**
